### ISSUE TITLE
Cannot read saved weights

### ISSUE THREAD

**Issue by saskra** [nibtehaz/MultiResUNet#11]
I really love this project, but now I faced my first problem. I used your function to save the model:
```python
def saveModel(model):
    model_json = model.to_json()
    try:
        os.makedirs('models')
    except:
        pass
    fp = open('models/modelP.json','w')
    fp.write(model_json)
    model.save_weights('models/modelW.h5')
```

And I tried to read it like this:
```python
def load_model(model_dir):
	# load json and create model
	json_file = open(model_dir + 'modelP.json', 'r')
	loaded_model_json = json_file.read()
	json_file.close()
	loaded_model = model_from_json(loaded_model_json)
	# load weights into new model
	loaded_model.load_weights(model_dir + "modelW.h5")
	loaded_model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
	print("Loaded model from " + model_dir)
	return loaded_model
```

But that is the error message I get when I try to use "load_weights" - at least for some of the files:
```shell
  File "/home/x/anaconda3/envs/MultiResUNet/lib/python3.7/site-packages/h5py/_hl/files.py", line 312, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/home/x/anaconda3/envs/MultiResUNet/lib/python3.7/site-packages/h5py/_hl/files.py", line 142, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 78, in h5py.h5f.open
OSError: Unable to open file (bad object header version number)
```

Any chance I can recover my hard trained models?

**Comment by nibtehaz** [comment]
Hello, sorry for such a delayed response. I'm really delighted to know that you've liked our project.

Looking at your error and seeing this stack overflow post https://stackoverflow.com/questions/26613570/hdf5-file-created-with-h5py-cant-be-opened-by-h5py

it appears to me that some accident might have happened during saving the file. Since model.save_weights() is a standard keras function it is very unlikely that it has caused any issues. Most likely for some unknwon reason the hdf5 file got corrupted.

Sorry I couldn't be much helpful.

**Comment by saskra** [comment]
Thanks for your answer, I think I found the solution: You have to add "fp.close()" to your function! Unfortunately, I does only help for future models, not for those already saved.
