### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by HuangQinJian** [nibtehaz/MultiResUNet#2]
Is there more complete code(sunch as training process,dataset)?

**Comment by nibtehaz** [comment]
Hello. The training process is just using the standard keras commands like model.compile, model.fit etc. And the datasets are publicly available. Just download the data, resize them and train :)

**Comment by nikola-t** [comment]
Hello!
Do you have some example code for multi GPU training? Is it possible to implement it in your's code?

**Comment by nibtehaz** [comment]
Hi @nikola-t , sorry I haven't worked with multiple GPUs before. However, since this implementation is merely a plain Keras model, anything possible for Keras models should be possible as well.

Please have a look at this link
https://datascience.stackexchange.com/questions/23895/multi-gpu-in-keras

Hope this helps. Thank you. Have a great day.
