### ISSUE TITLE
Train in my own dataset

### ISSUE THREAD

**Issue by AmericaBG** [nibtehaz/MultiResUNet#21]
Hi!
First of all, thank you very much for sharing your project. It's a great job, congratulations!

I would like to train your network with my own dataset. I've .nii files, so, what I should to do is to stack all my dataset in a numpy array?
For example, if I've 20 .nii files with shape [20,256,256], I create an array of [400,256,256]. That's it?

Thank you ver much in advance.

All the best :)

**Comment by nibtehaz** [comment]
Hi @SouthAmericaB 

Thank you for your kind words and your interest in our project.

Yes exactly, if you wish to use the 2D model you would need to convert the data from 20 20x256x256 arrays to 1 400x256x256 array.

On the other hand if you wish to use the 3D model you would need to convert that to 20 (number of files) x 256 (X direction) x 256 (Y direction) x 20 (Z direction). Since the number of pixels along the Z direction (20) is too low, that may not yield good result.

Thanks again, best wishes with your work.

**Comment by AmericaBG** [comment]
Thank you very  much about your reply! 

I'm going to try :D

All the best!

**Comment by nibtehaz** [comment]
You're most welcome, best wishes.
